package ExceptionHandling;

public class TryWithMultipleCatch {
public static void main(String[] args) {
	System.out.println("Hi");
//	try {
//		System.out.println(10/0);
//	}

	catch(ArithmeticException e) {
		System.out.println(10/2);
	}
//	catch(Exception e) {
//		System.out.println("test");
//	}
//	catch(ArithmeticException e) {
//		System.out.println(10/2);
//	}
	finally {
		System.out.println("closing");
	}
	
	System.out.println("Bye");
	
	
	
	
}
}
